# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lucas Tayrone Moreira
title: Senior Consultant Supply Chain and Operations
email: lucas.tayrone@hotmail.com
website: www.github.com/ltayrone

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  LTayrone
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: tayrone.lucas
linkedin_username: lucastayrone-data-analyst
# youtube_username: globalmtb


# Additional icon links
#additional_links:
#- title: itsgoingto.be
  #icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Tenho uma ampla experiência em Business Intelligence e Pesquisa Operacional, com foco na aplicação de algoritmos de otimização combinatória. 
  Atualmente, estou em um momento de transição de carreira para a área de Data Science, com um enfoque específico em algoritmos de otimização exatos e heurísticos.
  Tenho uma formação acadêmica sólida, além de estar atualmente cursando um mestrado em Modelagem Matemática e Computacional. 
  Essa trajetória acadêmica me proporcionou uma base sólida em análise de dados e habilidades avançadas em programação unificados ao meu perfil multidisciplinar de consultoria. 

  Estou constantemente buscando atualizações e aprimoramento em minha área de atuação, com o objetivo de entregar soluções eficazes e inovadoras para meus clientes.
  Tenho paixão por desafios complexos e gosto de aplicar minha expertise para encontrar soluções personalizadas que impulsionem a eficiência operacional e a tomada de decisões estratégicas.
  Estou sempre em busca de novas oportunidades para aplicar minha experiência e conhecimentos em projetos de otimização de alto impacto.

  Além disso, possuo uma vasta experiência trabalhando como consultor em grandes empresas do setor de consultoria, onde desenvolvi soluções estratégicas para otimização de processos e redução de custos.
  Ao longo da minha carreira, tive a oportunidade de liderar equipes multidisciplinares e implementar mudanças efetivas nos fluxos de produção.
  Estou entusiasmado em adentrar a área de Data Science, onde poderei aplicar meu conhecimento em algoritmos de otimização em conjunto com técnicas de aprendizado de máquina e análise de dados. 
  
  Tenho interesse especial em desenvolver soluções que impulsionem a eficiência operacional e a tomada de decisões estratégicas nas empresas.
  Minhas principais habilidades são: <mark>Diagnóstico e Modelagem de Processos</mark>, <mark>Power BI</mark>, <mark>Analise Exploratória</mark>, <mark>Modelagem Matemática</mark>, <mark>Pesquisa Operacional</mark>.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: EY | Ernst & Young
        link: www.ey.com
        # link_text: boringcompany.com
        sub_title: Senior Consultant Supply Chain and Operations
        caption: Setembro 2021 - Present
        quote: >
          Senior Consultant em Supply Chain and Operations com foco em Mineração e Metais.
        description: | # this will include new lines to allow paragraphs
          Especialista em diagnóstico, implementação de processos e desenvolvimento de negócios.
          Conectado globalmente para fornecer soluções de alto valor aos clientes. Agente transformador, identificando riscos e oportunidades para impulsionar resultados excepcionais.
          Utilizo técnicas avançadas de análise de dados e mapeamento de processos para identificar oportunidades de melhoria e propor soluções de alto valor para nossos clientes.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Alvarez & Marsal
        link: www.alvarezandmarsal.com/pt-br
        # link_text: boringcompany.com
        sub_title: Consultant I&CP | Infrastructure & Capital Projects 
        caption: Abril 2021 - Setembro 2021
        quote: >
          Consultant em Infrastructure & Capital Projects com foco em Construção Civil Pesada.
        description: | # this will include new lines to allow paragraphs
          Como Advisor em Infraestrutura e Projetos de Capital, atuo em diversas áreas-chave, incluindo infraestrutura, estratégias de aquisição, monitoramento de construção, construção enxuta, reestruturação do negócio central, escritório enxuto e transformação digital. Com vasto conhecimento e experiência, otimizo projetos de infraestrutura, garantindo eficiência, economia e entrega pontual. Ofereço aconselhamento estratégico em processos de aquisição, permitindo decisões informadas e alcançando metas de projeto. Além disso, forneço serviços abrangentes de monitoramento de construção, garantindo que os projetos atendam aos padrões de qualidade e requisitos de conformidade.
          Através de princípios de construção enxuta, auxilio os clientes na otimização de operações, redução de desperdícios e aumento da produtividade.
          Também apoio a transformação digital, impulsionando inovação e eficiência.

  - title: # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Drogaria Araujo
        link: www.araujo.com.br
        # link_text: boringcompany.com
        sub_title: Continuous Improvement Analyst | Internal Consultant 
        caption: Junho 2020 - Abril 2021
        quote: >
         Lean Specialist - Kaizen Practitioner.
        description: | # this will include new lines to allow paragraphs
          Trabalhei como consultor interno especializado em Kaizen na rede de farmácias Araújo.
          Responsável por implementar e apoiar o sistema de gestão e projetos de melhoria baseados na metodologia Kaizen.
          Ofereci suporte metodológico para sustentar, manter e desenvolver o programa na empresa.
          Elaborei e revisei documentos relacionados à metodologia e aos projetos.
          Atuei na automação de processos, inovação e transformação das rotinas do setor, mudando as formas de controle por meio do uso de ferramentas atuais com baixo ou nenhum custo.

  - title: # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Anglogold Ashanti
        link: www.anglogoldashanti.com.br
        # link_text: boringcompany.com
        sub_title: Business Improvement Analyst | Business Analyst 
        caption: Maio 2019 - Junho 2020
        quote: >
         Business Analyst
        description: | # this will include new lines to allow paragraphs
          Realizei o monitoramento dos cronogramas de processo de produção. Monitorei riscos operacionais, desvios operacionais e de processos. 
          Desenvolvi planos de melhoria contínua e controle de custos e variações operacionais. Elaborei planos preventivos contra acidentes e incidentes nos postos de trabalho. 
          Gerenciei as boas Práticas de Fabricação baseadas no Ciclo PDCA. Identifiquei desperdícios e não conformidades nos processos de produção. Realizei o controle do setor e 
          gestão de projetos de Saúde, Segurança e Meio Ambiente. Bem comoa realização de monitorar os procedimentos de Saúde, Segurança e Meio Ambiente e indicadores de desempenho (KPIs) na área de EHS. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Centro Federal de Educação Tecnológica de Minas Gerais
        caption: 2022 - atualmente
        sub_title: MSc Modelagem Matemática e Computacional
        quote: >
          O Centro Federal de Educação Tecnológica de Minas Gerais (CEFET-MG) é uma autarquia federal brasileira, vinculada ao Ministério da Educação, que oferece ensino médio, cursos técnicos, superiores, pós stricto sensu e lato sensu, contemplando também, de forma indissociada, o ensino, a pesquisa e a extensão, na área tecnológica e no âmbito da pesquisa aplicada.
        description: | # this will include new lines to allow paragraphs
          Estudo com foco na area de Otimização Combinatoria: Heuristicas Computacionais, Programação Linear Inteira, Industria 4.0 e Princípios de Modelagem Matemática.
          Utilização de Linguagem de Programação Python e C++.

  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Centro Universitario Métodista Izabela Hendrix
        caption: 2015 - 2018
        sub_title: BSc Engenharia de Produção
        quote: >
          O Centro Universitário Metodista Izabela Hendrix é uma Instituição Confessional Comunitária de Educação Superior, nos termos da Lei nº 12.881, de 12 de novembro de 2013.
          Isso significa que tem um modelo diferenciado de atuação, cujas características são marcadas pela natureza pública de seus atos instituidores, pela regionalidade de atuação e pelo seu comprometimento com o processo de desenvolvimento de Minas Gerais,
          especialmente na Região Metropolitana de Belo Horizonte.
          Em 2017, a publicação Guia do Estudante, da Editora Abril, avaliou os cursos de graduação oferecidos pelo Centro Universitário e considerou o Izabela Hendrix como o melhor centro universitário privado de Minas Gerais.
        description: | # this will include new lines to allow paragraphs
          Estudo com foco na area de Otimização Combinatoria e Planejamento e Controle da Produção: Estudos em sistemas eletricos, mecanicos e fundamentos de ciencia dos materiais graduação com ênfase em métodos de tomada de decisão baseados em dados: Pesquisa Operacional: Otimização e Simulação de Eventos Discretos. 

  - title:  # Title for the section
      layout: list # Type of content section (list/text)
      content:
        - layout: left
          title:  Business School Brasil - Escola de Negócios
          caption: 2021 - 2023
          sub_title: MBA em Pesquisa Operacional e Tomada de Decisão
          description: | # this will include new lines to allow paragraphs
            Métodos de tomada de decisão baseados em dados, modelagem matemática e computacional de problemas de tomada de decisão em horizontes operacionais, 
            táticos e estratégicos, utilizando técnicas de tomada de decisão multicritério e otimização combinatorial.  


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
        Apaixonado por aprendizado e por culinaria amadora, divido o meu tempo entre esses temas e jogos digitais de MMO RPG e Moba.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
