# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lucas Tayrone
title: Senior Consultant
email: lucas.tayrone@hotmail.com
website: www.github.com/ltayrone

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: facespics
github_username:  LTayrone
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: tayrone.lucas
linkedin_username: lucastayrone-data-analyst

# youtube_username: globalmtb


# Additional icon links
#additional_links:
#- title: itsgoingto.be
  #icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Olá, meu nome é Lucas Tayrone, sou Consultor Sênior de Supply Chain, Engenheiro de Produção e Segurança do Trabalho com especialização em Business Inteligence e Pesquisa Operacional.
 Atualmente sou estudante de mestrado no programa de Modelagem Matematica e Computacional, com foco em algoritmos de otimização combinatoria. Em fase de transição de carreira para area de Data Science com foco
 em algoritmos de otimização exatos e heuristicos. 

  Minhas principais habilidades são: <mark>Power BI</mark>, <mark>Analise Exploratória</mark>, <mark>Modelagem Matemática</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: EY | Ernst & Young
        link: www.ey.com
        # link_text: boringcompany.com
        sub_title: Senior Consultant Supply Chain and Operations
        caption: Setembro 2021 - Present
        quote: >
          Atuação estrategica com os cliente em toda cadeia de valor, proposta de melhoria de processos e tomada de decisão baseada em dados.
        description: | # this will include new lines to allow paragraphs
            Em construção ....

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Centro Federal de Educação Tecnológica de Minas Gerais
        caption: 2022 - atualmente
        sub_title: MSc Modelagem Matemática e Computacional
        quote: >
          O Centro Federal de Educação Tecnológica de Minas Gerais (CEFET-MG) é uma autarquia federal brasileira, vinculada ao Ministério da Educação, que oferece ensino médio, cursos técnicos, superiores, pós stricto sensu e lato sensu, contemplando também, de forma indissociada, o ensino, a pesquisa e a extensão, na área tecnológica e no âmbito da pesquisa aplicada.
        description: | # this will include new lines to allow paragraphs
          em construção...


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
